stages:
  - build
  - docker-rno-deploy
  - docker-sa-deploy

image: creatiwww/docker-compose:latest

react-build:
  stage: build
  tags:
    - test
  image: node:18.16.1-alpine
  script: 
    - echo "Start building App"
    - cd frontend
    - npm install next
    - npm install .
    - npm run build
    - echo "Build successfully!"
  artifacts:
    paths:
      - frontend/out

docker-react-nextjs-openvidu-deploy:
  stage: docker-rno-deploy
  tags:
  - test
  image: docker:latest
  services: 
    - docker:19.03.8-dind
  before_script:
    - echo "$DOCKER_HUB_PW" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  script:
    - cd frontend
    - cp -r ./out /home/ubuntu/S09P12A602/openvidu
    - cd ../openvidu
    - ./openvidu start
  after_script:
    - docker logout

docker-spring-api-mariadb-redis-deploy:
  image: docker:latest
  stage: docker-sa-deploy
  tags:
    - test
  services:
    - docker:19.03.8-dind
  before_script:
    - echo "$DOCKER_HUB_PW" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  script:
    - docker-compose down
    - docker-compose up -d
  after_script:
    - docker logout
