stages:
  - build
#  - test
  - package
  - deploy

build:
  image: openjdk:17-jdk-alpine # Dockerfile의 JDK 이미지
  stage: build
  tags:
    - test
  script:
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 10 min
  only:
    - deploy

#test:
#  image: openjdk:17-jdk-alpine
#  stage: test
#  script:
#    - ./gradlew test

package:
  image: docker:latest
  stage: package
  tags:
    - test
  variables:
    IMAGE_NAME: zaqxsw1397/spring-api
  services:
    - docker:19.03.8-dind
  before_script:
    - docker login -u $DOCKER_HUB_USER --password-stdin < $DOCKER_HUB_PW
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  after_script:
    - docker logout
  only:
    - deploy

deploy-was1:
  stage: deploy
  tags:
    - test
  before_script:
    - docker login -u $DOCKER_HUB_USER --password-stdin < $DOCKER_HUB_PW
  script:
    - docker stop SPRINGAPI || true
    - docker rm SPRINGAPI || true
    - docker rmi zaqxsw1397/spring-api || true
    - docker run -d --restart always -p 8443:8443 --name SPRINGAPI zaqxsw1397/spring-api
  after_script:
    - docker logout
  when: on_success
  only:
    - deploy